version: '3.4'

services:
  mongo:
    container_name: sourcingdb
    restart: always
    volumes:
      - ${APPDATA}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"    
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mssql:
    container_name: sourcingsqldb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"
  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ProductMongoDbSettings:ConnectionString=mongodb://mongo:27017"
    depends_on:
      - mongo
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SourcingMongoDbSettings:ConnectionString=mongodb://mongo:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - mongo
      - rabbitmq 
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  esourcing.order:
    container_name: esourcingorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Database=OrderDb;User Id=sa;Password=Odb12345678;TrustServerCertificate=true"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - mssql
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "8002:80"


  esourcing.apigateway:
    container_name: esourcingapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - esourcing.products
      - esourcing.sourcing
      - esourcing.order
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

