version: '3.4'

services:
  esourcing.products:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: ESourcing.Products/Dockerfile
  mongo:
    image: mongo

  esourcing.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
      context: .
      dockerfile: ESourcing.Sourcing/Dockerfile

